import type { Config } from 'tailwindcss'

const config: Config = {
  darkMode: 'class',
  content: [
    './src/pages/**/*.{js,ts,jsx,tsx,mdx}',
    './src/components/**/*.{js,ts,jsx,tsx,mdx}',
    './src/app/**/*.{js,ts,jsx,tsx,mdx}',
  ],
  theme: {
    extend: {
      colors: {
        'surface-tint': '#cc0000',
        'secondary-fixed-dim': '#333333',
        'surface-container-low': '#f5f5f5',
        'primary-fixed': '#ffcccc',
        'on-error-container': '#93000a',
        'tertiary-fixed-dim': '#c8c6c5',
        'secondary-fixed': '#ffe170',
        'surface-container': '#f5f5f5',
        'secondary-container': '#fdd400',
        'on-tertiary': '#ffffff',
        'on-tertiary-fixed': '#1c1b1b',
        'on-secondary-fixed': '#221b00',
        'tertiary-fixed': '#e5e2e1',
        'on-tertiary-fixed-variant': '#474746',
        'on-secondary-fixed-variant': '#544600',
        'outline': '#888888',
        'primary': '#cc0000',
        'secondary': '#1a1a1a',
        'surface-container-high': '#eeeeee',
        'error': '#ba1a1a',
        'surface-container-lowest': '#ffffff',
        'on-primary': '#ffffff',
        'surface-bright': '#ffffff',
        'tertiary': '#5f5e5e',
        'tertiary-container': '#949292',
        'surface-dim': '#e8e0e0',
        'on-secondary': '#ffffff',
        'on-primary-container': '#cc0000',
        'background': '#ffffff',
        'on-secondary-container': '#6f5c00',
        'surface-container-highest': '#ece7e7',
        'inverse-surface': '#2e3132',
        'surface-variant': '#e1e3e4',
        'surface': '#ffffff',
        'error-container': '#ffdad6',
        'inverse-primary': '#cc0000',
        'primary-fixed-dim': '#ffaaaa',
        'outline-variant': '#e2e2e2',
        'on-primary-fixed': '#172554',
        'primary-container': '#ffcccc',
        'inverse-on-surface': '#f0f1f2',
        'on-error': '#ffffff',
        'on-primary-fixed-variant': '#b30000',
        'on-surface': '#111111',
        'on-tertiary-container': '#2c2b2b',
        'on-surface-variant': '#888888',
        'on-background': '#111111',
        'button': '#cc0000',
        'button-hover': '#b30000',
        'border': '#e2e2e2',
        'card': '#ffffff',
        'muted-foreground': '#888888',
      },
      borderRadius: {
        'DEFAULT': '0.125rem',
        'sm': '4px',
        'md': '6px',
        'lg': '8px',
        'xl': '20px',
        'full': '9999px',
      },
      spacing: {
        'stack-lg': '48px',
        'stack-md': '24px',
        'stack-sm': '12px',
        'section-gap': '64px',
        'margin-mobile': '16px',
        'container-max': '1280px',
        'stack-xs': '4px',
        'base': '8px',
        'gutter': '24px',
      },
      fontFamily: {
        'inter': ['Inter', 'sans-serif'],
        'headline-lg-mobile': ['Inter', 'sans-serif'],
        'display-hero-mobile': ['Inter', 'sans-serif'],
        'headline-lg': ['Inter', 'sans-serif'],
        'body-lg': ['Inter', 'sans-serif'],
        'headline-md': ['Inter', 'sans-serif'],
        'display-hero': ['Inter', 'sans-serif'],
        'label-caps': ['Inter', 'sans-serif'],
        'label-category': ['Inter', 'sans-serif'],
        'body-md': ['Inter', 'sans-serif'],
      },
      fontSize: {
        'headline-lg-mobile': ['24px', { lineHeight: '30px', fontWeight: '600' }],
        'display-hero-mobile': ['32px', { lineHeight: '38px', letterSpacing: '-0.01em', fontWeight: '700' }],
        'headline-lg': ['32px', { lineHeight: '40px', fontWeight: '600' }],
        'body-lg': ['18px', { lineHeight: '28px', fontWeight: '400' }],
        'headline-md': ['24px', { lineHeight: '32px', fontWeight: '600' }],
        'display-hero': ['48px', { lineHeight: '56px', letterSpacing: '-0.02em', fontWeight: '700' }],
        'label-caps': ['12px', { lineHeight: '16px', letterSpacing: '0.05em', fontWeight: '700' }],
        'label-category': ['14px', { lineHeight: '18px', fontWeight: '600' }],
        'body-md': ['16px', { lineHeight: '24px', fontWeight: '400' }],
      },
    },
  },
  plugins: [
    require('@tailwindcss/typography'),
  ],
}
export default config
